-- ============================================================================
--  DrShompa — PostgreSQL schema + sample data
--
--  চালান / Run it with:
--      npm.cmd run db:migrate
--  (টেবিল + sample data একবারেই তৈরি হয়; বারবার চালালেও কিছু নষ্ট হয় না)
--
--  The script is idempotent: running it again never duplicates a row and never
--  drops data. server.js also runs it automatically at startup
--  (switch that off with DB_AUTO_MIGRATE=false).
--
--  Table and column names are quoted on purpose, so PostgreSQL keeps the exact
--  casing the API and the frontend already use ("PatientName", "PreferredDate",
--  ...). Never recreate these tables with unquoted names — PostgreSQL would
--  fold them to lower case and every API response would suddenly use
--  different field names.
-- ============================================================================

-- 1. Appointments ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Appointments" (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientName"   VARCHAR(150) NOT NULL,
    "Age"           INTEGER NOT NULL,
    "Phone"         VARCHAR(30) NOT NULL,
    "VisitType"     VARCHAR(50) NOT NULL,
    "PreferredDate" DATE NOT NULL,
    "PreferredSlot" VARCHAR(50) NOT NULL,
    "Notes"         TEXT NULL,
    "Status"        VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "CreatedAt"     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Index used by the protected appointment dashboard and the reminder queries.
CREATE INDEX IF NOT EXISTS "IX_Appointments_PreferredDate_Status"
    ON "Appointments" ("PreferredDate", "Status")
    INCLUDE ("CreatedAt", "PatientName", "Phone", "PreferredSlot");

-- 2. SiteSettings (key → value storage used by the CMS) ----------------------
CREATE TABLE IF NOT EXISTS "SiteSettings" (
    "SettingKey"   VARCHAR(100) PRIMARY KEY,
    "SettingValue" TEXT NOT NULL,
    "UpdatedAt"    TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Default site content. ON CONFLICT DO NOTHING means an existing value is
-- never overwritten by a migration run.
INSERT INTO "SiteSettings" ("SettingKey", "SettingValue") VALUES
    ('doctor_name', 'Dr. Arefin Zannat Sompa'),
    ('doctor_title', 'Consultant Psychiatrist — Department of Psychiatry, Sylhet MAG Osmani Medical College'),
    ('location_kicker', 'SYLHET, BANGLADESH'),
    ('lede_text', 'Assessment and treatment for depression, anxiety, sleep difficulty, and other mental health conditions — for adults and adolescents, in a calm and confidential setting.'),
    ('degree_1', 'MD | Psychiatry, BMU'),
    ('degree_2', 'BCS | Health cadre'),
    ('degree_3', 'SOMC | Teaching hospital'),
    ('phone', '01339059043'),
    ('email', 'sompa.szmc@gmail.com'),
    ('chamber_address', 'Sylhet, Bangladesh (Near Sylhet MAG Osmani Medical College)'),
    ('chamber_hours', 'Sat–Thu, evening chamber hours'),
    ('email_hint', 'Replies within two working days'),
    ('maps_url', 'https://maps.google.com/?q=Sylhet+MAG+Osmani+Medical+College'),
    ('doctor_photo', 'dr_sompa_portrait.jpg'),
    ('chamber_photo', 'clinic_ambience.jpg'),
    ('wellness_photo', 'mental_wellness_care.jpg'),
    ('site_logo', '')
ON CONFLICT ("SettingKey") DO NOTHING;

-- 3. Services ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Services" (
    "Id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"       VARCHAR(150) NOT NULL,
    "Description" TEXT NOT NULL,
    "SortOrder"   INTEGER NOT NULL DEFAULT 0,
    "IsActive"    BOOLEAN NOT NULL DEFAULT TRUE
);

-- Seed sample rows only when the table is still empty (so an admin who deleted
-- a service never gets it back after a restart).
INSERT INTO "Services" ("Title", "Description", "SortOrder")
SELECT seed."Title", seed."Description", seed."SortOrder"
FROM (VALUES
    ('Depression & mood', 'Low mood, loss of interest, bipolar disorder, and postpartum depression.', 1),
    ('Anxiety & panic', 'Generalised anxiety, panic attacks, phobia, and obsessive-compulsive disorder.', 2),
    ('Sleep problems', 'Insomnia, disturbed sleep cycles, and sleep difficulty linked to stress.', 3),
    ('Adolescent mental health', 'Exam stress, behavioural change, and school or family difficulty in teenagers.', 4),
    ('Psychotic illness', 'Schizophrenia and related conditions, with long-term follow-up and family guidance.', 5),
    ('Addiction support', 'Substance use assessment, withdrawal management, and relapse prevention planning.', 6)
) AS seed("Title", "Description", "SortOrder")
WHERE NOT EXISTS (SELECT 1 FROM "Services");

-- 4. Testimonials ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Testimonials" (
    "Id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Quote"     TEXT NOT NULL,
    "Author"    VARCHAR(150) NOT NULL,
    "SortOrder" INTEGER NOT NULL DEFAULT 0,
    "IsActive"  BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO "Testimonials" ("Quote", "Author", "SortOrder")
SELECT seed."Quote", seed."Author", seed."SortOrder"
FROM (VALUES
    ('She explained my diagnosis in words my family could follow. For the first time we understood what was happening.', 'PATIENT''S DAUGHTER, SYLHET', 1),
    ('No rush, no judgement. She asked questions nobody had asked me before, and the treatment plan actually made sense.', 'PATIENT, 34', 2),
    ('My son refused to see a doctor for months. After one session with her, he agreed to continue treatment.', 'PARENT, MOULVIBAZAR', 3)
) AS seed("Quote", "Author", "SortOrder")
WHERE NOT EXISTS (SELECT 1 FROM "Testimonials");

-- 5. Qualifications ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Qualifications" (
    "Id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"       VARCHAR(150) NOT NULL,
    "Description" TEXT NOT NULL,
    "Subtext"     VARCHAR(150) NOT NULL,
    "SortOrder"   INTEGER NOT NULL DEFAULT 0
);

INSERT INTO "Qualifications" ("Title", "Description", "Subtext", "SortOrder")
SELECT seed."Title", seed."Description", seed."Subtext", seed."SortOrder"
FROM (VALUES
    ('Qualifications', 'MBBS, BCS (Health), MD in Psychiatry.', 'Bangladesh Medical University', 1),
    ('Current position', 'Department of Psychiatry, Sylhet MAG Osmani Medical College (SOMC).', 'Sylhet, Bangladesh', 2),
    ('Care philosophy', 'Listening first, explaining clearly, and treating each person with dignity.', 'Empathy. Expertise. Excellence.', 3)
) AS seed("Title", "Description", "Subtext", "SortOrder")
WHERE NOT EXISTS (SELECT 1 FROM "Qualifications");

-- 6. ReminderLog (SMS / e-mail history behind the reminder panel) ------------
-- AppointmentId 0 = a whole-day e-mail digest, so there is deliberately no
-- foreign key here (same behaviour as the original SQL Server schema).
CREATE TABLE IF NOT EXISTS "ReminderLog" (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AppointmentId" INTEGER NOT NULL,
    "Channel"       VARCHAR(20) NOT NULL,
    "Destination"   VARCHAR(200) NOT NULL,
    "Message"       TEXT NOT NULL,
    "Status"        VARCHAR(20) NOT NULL,
    "Error"         TEXT NULL,
    "SentAt"        TIMESTAMP NOT NULL DEFAULT NOW()
);

